### ISSUE TITLE
Logotipo para a comunidade

### ISSUE THREAD

**Issue by valescaf** [sysadminas/docs#2]
Nós gostaríamos de um logotipo para a comunidade inspirado nessa imagem: https://cdn-images-1.medium.com/fit/c/200/200/1*pEKUBjzayS3uP4cTi6i-zw.jpeg. Ao invés de system administrator, seria apenas SYSADMINAS.

**Comment by thebeaoliveira** [comment]
Criado :)

**Comment by thebeaoliveira** [comment]
![photo_2020-01-29 21 25 19](https://user-images.githubusercontent.com/24916088/73616970-c3f46080-45f8-11ea-8c91-0d898d550a0e.jpeg)
